
FROM node:18

WORKDIR /app

COPY package.json package-lock.json ./


RUN npm install --production


COPY . .


RUN npx prisma generate


RUN npx prisma migrate deploy


EXPOSE 5000


CMD ["node", "app.js"]
